package com.inventory.app.domain;

import java.util.Arrays;
import java.util.Date;

public class ItemVO {
	private Long itemSeq;
	private String itemName;
	private Long itemPrice;
	private Date itemExdate;
	private Short itemSize;
	private Date itemRegdate;
	private Date itemFwdate;
	private String itemDesc;
	private String itemMaker;
	private byte[] itemImg;

	public ItemVO() {
		super();
	}

	public ItemVO(Long itemSeq, String itemName, Long itemPrice, Date itemExdate, String itemMaker) {
		super();
		this.itemSeq = itemSeq;
		this.itemName = itemName;
		this.itemPrice = itemPrice;
		this.itemExdate = itemExdate;
		this.itemMaker = itemMaker;
	}

	public Long getItemSeq() {
		return itemSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_SEQ
	 *
	 * @param itemSeq the value for ITEM.ITEM_SEQ
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemSeq(Long itemSeq) {
		this.itemSeq = itemSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_NAME
	 *
	 * @return the value of ITEM.ITEM_NAME
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_NAME
	 *
	 * @param itemName the value for ITEM.ITEM_NAME
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName == null ? null : itemName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_PRICE
	 *
	 * @return the value of ITEM.ITEM_PRICE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public Long getItemPrice() {
		return itemPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_PRICE
	 *
	 * @param itemPrice the value for ITEM.ITEM_PRICE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemPrice(Long itemPrice) {
		this.itemPrice = itemPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_EXDATE
	 *
	 * @return the value of ITEM.ITEM_EXDATE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public Date getItemExdate() {
		return itemExdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_EXDATE
	 *
	 * @param itemExdate the value for ITEM.ITEM_EXDATE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemExdate(Date itemExdate) {
		this.itemExdate = itemExdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_SIZE
	 *
	 * @return the value of ITEM.ITEM_SIZE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public Short getItemSize() {
		return itemSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_SIZE
	 *
	 * @param itemSize the value for ITEM.ITEM_SIZE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemSize(Short itemSize) {
		this.itemSize = itemSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_REGDATE
	 *
	 * @return the value of ITEM.ITEM_REGDATE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public Date getItemRegdate() {
		return itemRegdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_REGDATE
	 *
	 * @param itemRegdate the value for ITEM.ITEM_REGDATE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemRegdate(Date itemRegdate) {
		this.itemRegdate = itemRegdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_FWDATE
	 *
	 * @return the value of ITEM.ITEM_FWDATE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public Date getItemFwdate() {
		return itemFwdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_FWDATE
	 *
	 * @param itemFwdate the value for ITEM.ITEM_FWDATE
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemFwdate(Date itemFwdate) {
		this.itemFwdate = itemFwdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_DESC
	 *
	 * @return the value of ITEM.ITEM_DESC
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public String getItemDesc() {
		return itemDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_DESC
	 *
	 * @param itemDesc the value for ITEM.ITEM_DESC
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc == null ? null : itemDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_MAKER
	 *
	 * @return the value of ITEM.ITEM_MAKER
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public String getItemMaker() {
		return itemMaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_MAKER
	 *
	 * @param itemMaker the value for ITEM.ITEM_MAKER
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemMaker(String itemMaker) {
		this.itemMaker = itemMaker == null ? null : itemMaker.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column ITEM.ITEM_IMG
	 *
	 * @return the value of ITEM.ITEM_IMG
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public byte[] getItemImg() {
		return itemImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column ITEM.ITEM_IMG
	 *
	 * @param itemImg the value for ITEM.ITEM_IMG
	 *
	 * @mbg.generated Thu Nov 26 10:47:29 KST 2020
	 */
	public void setItemImg(byte[] itemImg) {
		this.itemImg = itemImg;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemDesc == null) ? 0 : itemDesc.hashCode());
		result = prime * result + ((itemExdate == null) ? 0 : itemExdate.hashCode());
		result = prime * result + ((itemFwdate == null) ? 0 : itemFwdate.hashCode());
		result = prime * result + Arrays.hashCode(itemImg);
		result = prime * result + ((itemMaker == null) ? 0 : itemMaker.hashCode());
		result = prime * result + ((itemName == null) ? 0 : itemName.hashCode());
		result = prime * result + ((itemPrice == null) ? 0 : itemPrice.hashCode());
		result = prime * result + ((itemRegdate == null) ? 0 : itemRegdate.hashCode());
		result = prime * result + ((itemSeq == null) ? 0 : itemSeq.hashCode());
		result = prime * result + ((itemSize == null) ? 0 : itemSize.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ItemVO other = (ItemVO) obj;
		if (itemDesc == null) {
			if (other.itemDesc != null)
				return false;
		} else if (!itemDesc.equals(other.itemDesc))
			return false;
		if (itemExdate == null) {
			if (other.itemExdate != null)
				return false;
		} else if (!itemExdate.equals(other.itemExdate))
			return false;
		if (itemFwdate == null) {
			if (other.itemFwdate != null)
				return false;
		} else if (!itemFwdate.equals(other.itemFwdate))
			return false;
		if (!Arrays.equals(itemImg, other.itemImg))
			return false;
		if (itemMaker == null) {
			if (other.itemMaker != null)
				return false;
		} else if (!itemMaker.equals(other.itemMaker))
			return false;
		if (itemName == null) {
			if (other.itemName != null)
				return false;
		} else if (!itemName.equals(other.itemName))
			return false;
		if (itemPrice == null) {
			if (other.itemPrice != null)
				return false;
		} else if (!itemPrice.equals(other.itemPrice))
			return false;
		if (itemRegdate == null) {
			if (other.itemRegdate != null)
				return false;
		} else if (!itemRegdate.equals(other.itemRegdate))
			return false;
		if (itemSeq == null) {
			if (other.itemSeq != null)
				return false;
		} else if (!itemSeq.equals(other.itemSeq))
			return false;
		if (itemSize == null) {
			if (other.itemSize != null)
				return false;
		} else if (!itemSize.equals(other.itemSize))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ItemVO [itemSeq=" + itemSeq + ", itemName=" + itemName + ", itemPrice=" + itemPrice + ", itemExdate="
				+ itemExdate + ", itemSize=" + itemSize + ", itemRegdate=" + itemRegdate + ", itemFwdate=" + itemFwdate
				+ ", itemDesc=" + itemDesc + ", itemMaker=" + itemMaker + ", itemImg=" + Arrays.toString(itemImg) + "]";
	}

}